### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by 649357610** [liuzhenboo/EKF-2D-SLAM#1]
你好，最近读了你的EKF-SLAM的程序，但状态增广，协方差计算那不太明白，想请教一下为什么要这样计算那？
![33](https://user-images.githubusercontent.com/59716628/77298386-d13ee900-6d25-11ea-85cd-18d26904087f.png)

**Comment by liuzhenboo** [comment]
（1）第一个式子
新增状态是由机器人状态和测量值计算得到的。假设新增路标状态记为X_l，机器人状态记为X_r，测量值记为Y，那么这三者线性关系可以写为X_l=aX_r+bY+K_0，其中a是X_l对X_r的雅可比，b是X_l对Y的雅可比，根据协方差的性质可求出结果。
（2）第二个式子
记状态扩增之前的系统状态为x。互协方差COV(X_l, x)=COV(aX_l, x)=aCOV(X_l, x)

**Comment by liuzhenboo** [comment]
> 你好，最近读了你的EKF-SLAM的程序，但状态增广，协方差计算那不太明白，想请教一下为什么要这样计算那？
> ![33](https://user-images.githubusercontent.com/59716628/77298386-d13ee900-6d25-11ea-85cd-18d26904087f.png)

第一个式子：
新增状态是由机器人状态和测量值计算得到的。假设新增路标状态记为X_l，机器人状态记为X_r，测量值记为Y，那么这三者线性关系可以写为X_l=aX_r+bY+K_0，其中a是X_l对X_r的雅可比，b是X_l对Y的雅可比，根据协方差的性质可求出结果。
第二个式子：
记状态扩增之前的系统状态为x。互协方差COV(X_l, x)=COV(aX_l, x)=aCOV(X_l, x)

**Comment by 649357610** [comment]
感谢回复！
第一个式子：
Cov(aX+bY,cW+dZ)=acCov(X,W)+bcCov(Y,M)+adCov(X,z)+bdCov(Y,Z)
如果Cov(X_r，Y)为0的话，才可以推出您的公式，但X_r和Y是相关的吧？
第二个式子:
我实在比较菜，还是理解不了，您能进一步讲解一下吗？
万分感谢！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Herbert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 晚上7:08
收件人:&nbsp;"liuzhenboo/EKF-2D-SLAM"<EKF-2D-SLAM@noreply.github.com&gt;;
抄送:&nbsp;"高帆"<649357610@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuzhenboo/EKF-2D-SLAM] 一个问题 (#1)





  
你好，最近读了你的EKF-SLAM的程序，但状态增广，协方差计算那不太明白，想请教一下为什么要这样计算那？
 
  
第一个式子：
 新增状态是由机器人状态和测量值计算得到的。假设新增路标状态记为X_l，机器人状态记为X_r，测量值记为Y，那么这三者线性关系可以写为X_l=aX_r+bY+K_0，其中a是X_l对X_r的雅可比，b是X_l对Y的雅可比，根据协方差的性质可求出结果。
 第二个式子：
 记状态扩增之前的系统状态为x。互协方差COV(X_l, x)=COV(aX_l, x)=aCOV(X_l, x)

**Comment by liuzhenboo** [comment]
> 感谢回复！ 第一个式子： Cov(aX+bY,cW+dZ)=acCov(X,W)+bcCov(Y,M)+adCov(X,z)+bdCov(Y,Z) 如果Cov(X_r，Y)为0的话，才可以推出您的公式，但X_r和Y是相关的吧？ 第二个式子: 我实在比较菜，还是理解不了，您能进一步讲解一下吗？ 万分感谢！ ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Herbert"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月23日(星期一) 晚上7:08 收件人:&nbsp;"liuzhenboo/EKF-2D-SLAM"<EKF-2D-SLAM@noreply.github.com&gt;; 抄送:&nbsp;"高帆"<649357610@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [liuzhenboo/EKF-2D-SLAM] 一个问题 (#1) 你好，最近读了你的EKF-SLAM的程序，但状态增广，协方差计算那不太明白，想请教一下为什么要这样计算那？ 第一个式子： 新增状态是由机器人状态和测量值计算得到的。假设新增路标状态记为X_l，机器人状态记为X_r，测量值记为Y，那么这三者线性关系可以写为X_l=aX_r+bY+K_0，其中a是X_l对X_r的雅可比，b是X_l对Y的雅可比，根据协方差的性质可求出结果。 第二个式子： 记状态扩增之前的系统状态为x。互协方差COV(X_l, x)=COV(aX_l, x)=aCOV(X_l, x) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

第一个：
Y是新的测量值。其噪声服从0均值高斯分布，只和传感器有关，独立于一切其他变量。COV(X_r, Y)=0
第二个：
X_l=aX_r+bY+K_0
COV(X_I, x)=COV(aX_r+bY+K_0, x)=COV(aX_l, x)+COV(bY, x)+COV(K_0, x)=COV(aX_l, x)=aCOV(X_l, x)

**Comment by 649357610** [comment]
哦哦，这回基本明白了，但怎么理解测量值Y与机器人状态X_r无关呢？这样的话怎么还能Y对X_r求雅克比？我有点乱了，求大师赐教




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Herbert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 晚上9:27
收件人:&nbsp;"liuzhenboo/EKF-2D-SLAM"<EKF-2D-SLAM@noreply.github.com&gt;;
抄送:&nbsp;"高帆"<649357610@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuzhenboo/EKF-2D-SLAM] 一个问题 (#1)





  
感谢回复！ 第一个式子： Cov(aX+bY,cW+dZ)=acCov(X,W)+bcCov(Y,M)+adCov(X,z)+bdCov(Y,Z) 如果Cov(X_r，Y)为0的话，才可以推出您的公式，但X_r和Y是相关的吧？ 第二个式子: 我实在比较菜，还是理解不了，您能进一步讲解一下吗？ 万分感谢！ ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Herbert"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月23日(星期一) 晚上7:08 收件人:&nbsp;"liuzhenboo/EKF-2D-SLAM"<EKF-2D-SLAM@noreply.github.com&gt;; 抄送:&nbsp;"高帆"<649357610@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [liuzhenboo/EKF-2D-SLAM] 一个问题 (#1) 你好，最近读了你的EKF-SLAM的程序，但状态增广，协方差计算那不太明白，想请教一下为什么要这样计算那？ 第一个式子： 新增状态是由机器人状态和测量值计算得到的。假设新增路标状态记为X_l，机器人状态记为X_r，测量值记为Y，那么这三者线性关系可以写为X_l=aX_r+bY+K_0，其中a是X_l对X_r的雅可比，b是X_l对Y的雅可比，根据协方差的性质可求出结果。 第二个式子： 记状态扩增之前的系统状态为x。互协方差COV(X_l, x)=COV(aX_l, x)=aCOV(X_l, x) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
第一个：
 Y是新的测量值，噪声服从0均值高斯分布，只和传感器有关，独立于一切其他变量，COV(X_r, Y)=0
 第二个：
 X_l=aX_r+bY+K_0
 COV(X_I, x)=COV(aX_r+bY+K_0, x)=COV(aX_l, x)+COV(bY, x)+COV(K_0, x)=COV(aX_l, x)=aCOV(X_l, x)

**Comment by liuzhenboo** [comment]
第一个问题：
我上面可能表达有点问题，“独立与一切变量”我指的是测量噪声，不是Y。具体COV(X_r，Y)的推导：
测量值Y=h(X_rr)+n。其中h是观测方程；n是测量噪声，与其他变量独立；X_rr是估计量X_r对应的真值，是个固定值，X_rr的协方差矩阵为0。所以COV(Y, X_r)=COV(h(X_rr), X_r)+COV(n, X_r)=0+0=0
第二个问题：
Y和X_r没有相关性，一般情况下只求h(X_rr)对X_rr的雅可比。
另外，观测值X_l=g(Y, X_r)，X_I与Y有相关性，可以求X_l对Y的雅可比。

**Comment by 649357610** [comment]
X_rr为什么是真值啊,他和X_r不是同一个随机变量吗，都表示机器人位姿吗？为什么X_rr是固定的值？啥叫做真值？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Herbert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 上午10:42
收件人:&nbsp;"liuzhenboo/EKF-2D-SLAM"<EKF-2D-SLAM@noreply.github.com&gt;;
抄送:&nbsp;"高帆"<649357610@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuzhenboo/EKF-2D-SLAM] 一个问题 (#1)





 
第一个问题：
 我上面可能表达有点问题，“独立与一切变量”我指的是测量噪声，不是Y。具体COV(X_r，Y)的推导：
 测量值Y=h(X_rr)+n。其中h是观测方程；n是测量噪声，与其他变量独立；X_rr是估计量X_r对应的真值，是个固定值，X_rr的协方差矩阵为0。所以COV(Y, X_r)=COV(h(X_rr), X_r)+COV(n, X_r)=0+0=0
 第二个问题：
 Y和X_r没有相关性，一般情况下只求h(X_rr)对X_rr的雅可比。
 另外，观测值X_l=g(Y, X_r)，X_I与Y有相关性，可以求X_l对Y的雅可比。

**Comment by liuzhenboo** [comment]
我仔细看了一下，当时我写的时候，是默认把(56)式中的y_n+1认为是(y_n+1)-v的。也就是说，(56)中的y_n+1是减去了噪声v的观测量，为了表述清晰，你可以把文章中的第（56）式子改成：L_n+1=g(R, S, y_n+1, v)，这样就好理解了。

第一个式子：
新增状态是由机器人状态和测量值计算得到的。假设新增路标状态记为X_l，机器人状态记为X_r，测量值记为Y，测量噪声为v，那么有X_l=g(X_r, Y, v)。用EKF展开得到：
X_l=g(X_r_, Y, 0)+a(X_r-X_r_)+b*0+c(v-0)，线性化点为(X_r_, Y, 0)。其中a是g对X_r的雅可比，b是g对Y的雅可比，c是g对v的雅可比，其中b=-c。
所以，COV(X_l, X_l)=COV(aX_r+cv, aX_r+cv)=COV(aX_r, aX_r)+COV(cv, cv)+2COV(aX_r, cv)=
aCOV(X_r, X_r)a^T + cCOV(v, v)c^T

第二个式子：
记状态扩增之前的系统状态为x。互协方差COV(X_l, x)=COV(aX_r+cv, x)=aCOV(X_r, x)

**Comment by 649357610** [comment]
不好意思，最近有些事，没有回复，我再按照你说的理解一下，真得非常感谢！



---原始邮件---
发件人: "Herbert"<notifications@github.com&gt;
发送时间: 2020年3月24日(星期二) 上午10:42
收件人: "liuzhenboo/EKF-2D-SLAM"<EKF-2D-SLAM@noreply.github.com&gt;;
抄送: "649357610"<649357610@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [liuzhenboo/EKF-2D-SLAM] 一个问题 (#1)




 
第一个问题：
 我上面可能表达有点问题，“独立与一切变量”我指的是测量噪声，不是Y。具体COV(X_r，Y)的推导：
 测量值Y=h(X_rr)+n。其中h是观测方程；n是测量噪声，与其他变量独立；X_rr是估计量X_r对应的真值，是个固定值，X_rr的协方差矩阵为0。所以COV(Y, X_r)=COV(h(X_rr), X_r)+COV(n, X_r)=0+0=0
 第二个问题：
 Y和X_r没有相关性，一般情况下只求h(X_rr)对X_rr的雅可比。
 另外，观测值X_l=g(Y, X_r)，X_I与Y有相关性，可以求X_l对Y的雅可比。
